apiVersion: v1
kind: Service
metadata:
  name: microservice-album-service
  labels:
    name: microservice-album-service
    app: microservice
spec:
  type: ClusterIP
  ports: 
    - port: 80
      targetPort: 80
  selector:
    app: microservice-album
    type: microservice