// <auto-generated />
using MicroBroker.Playlist.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroBroker.Playlist.Infraestructure.Migrations.PlaylistSongDb
{
    [DbContext(typeof(PlaylistSongDbContext))]
    [Migration("20230609061935_initial Migration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MicroBroker.Playlist.Domain.Models.PlaylistSong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Id_Playlist")
                        .HasColumnType("int");

                    b.Property<int>("Id_Song")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Playlist_Song");
                });
#pragma warning restore 612, 618
        }
    }
}
