CREATE DATABASE [BDD_BytesMusic_User];
GO

USE [BDD_BytesMusic_User];
GO

/****** Object:  Table [dbo].[TBL_USER]    Script Date: 11/6/2023 17:55:00 ******/
SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TBL_USER](
	[ID_USER] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[PASSWORD] [varchar](50) NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[BIRTHDAY] [datetime] NULL,
	[USER_PHOTO] [varchar](255) NULL,
	[USER_TYPE] [int] NOT NULL,
	CONSTRAINT [PK_TBL_USER] PRIMARY KEY CLUSTERED 
	(
		[ID_USER] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
