CREATE DATABASE [BDD_BytesMusic_Album];
GO

USE [BDD_BytesMusic_Album];
GO

/****** Object:  Table [dbo].[TBL_ALBUM]    Script Date: 11/6/2023 18:02:02 ******/
SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TBL_ALBUM](
	[ID_ALBUM] [int] IDENTITY(1,1) NOT NULL,
	[TITLE_ALBUM] [varchar](50) NOT NULL,
	[RELEASE_YEAR] [int] NULL,
	[ALBUM_IMAGE_PATH] [varchar](255) NULL,
	CONSTRAINT [PK__TBL_ALBU__2A24A9C5C68F7B29] PRIMARY KEY CLUSTERED 
	(
		[ID_ALBUM] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


USE [BDD_BytesMusic_Album];
GO

/****** Object:  Table [dbo].[TBL_TRACKLIST]    Script Date: 11/6/2023 18:02:23 ******/
SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TBL_TRACKLIST](
	[ID_ALBUM] [int] NOT NULL,
	[ID_SONG] [int] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	CONSTRAINT [PK_TBL_TRACKLIST] PRIMARY KEY CLUSTERED 
	(
		[ID_ALBUM] ASC,
		[ID_SONG] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

ALTER TABLE [dbo].[TBL_TRACKLIST]  WITH CHECK ADD CONSTRAINT [FK_TBL_TRACKLIST_TBL_ALBUM] FOREIGN KEY([ID_ALBUM])
REFERENCES [dbo].[TBL_ALBUM] ([ID_ALBUM]);
GO

ALTER TABLE [dbo].[TBL_TRACKLIST] CHECK CONSTRAINT [FK_TBL_TRACKLIST_TBL_ALBUM];
GO
