CREATE DATABASE [BDD_BytesMusic_Song];
GO

USE [BDD_BytesMusic_Song];
GO

/****** Object:  Table [dbo].[TBL_SONG]    Script Date: 11/6/2023 17:57:18 ******/
SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TBL_SONG](
	[ID_SONG] [int] IDENTITY(1,1) NOT NULL,
	[SONG_NAME] [varchar](50) NOT NULL,
	[SONG_PATH] [varchar](255) NOT NULL,
	[PLAYS] [int] NULL,
	CONSTRAINT [PK_TBL_SONG] PRIMARY KEY CLUSTERED 
	(
		[ID_SONG] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
