CREATE DATABASE [BDD_BytesMusic_Catalog];
GO

USE [BDD_BytesMusic_Catalog];
GO

/****** Object:  Table [dbo].[TBL_CATALOG]    Script Date: 11/6/2023 17:59:39 ******/
SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TBL_CATALOG](
	[ID_CATALOG] [int] IDENTITY(1,1) NOT NULL,
	[COD_CATALOG_PARENT] [varchar](8) NULL,
	[COD_CATALOG] [varchar](8) NULL,
	[VALUE] [varchar](255) NOT NULL,
 CONSTRAINT [PK_TBL_CATALOG] PRIMARY KEY CLUSTERED 
(
	[ID_CATALOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
